# Generated by Django 5.0.4 on 2024-05-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_historicalperformance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalPerformance',
            new_name='HistoricalPerformances',
        ),
    ]
