# Generated by Django 5.0.4 on 2024-05-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorders',
            name='quality_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
