# Generated by Django 5.0.4 on 2024-05-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0003_alter_purchaseorders_acknowledgement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorders',
            name='delivery_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
